deployment:
  tasks:
    # 1. Clear and Copy
    - rm -rf /home/dusatekc/mingook.dusatek.com/*
    - cp -r /home/dusatekc/repositories/mingook/* /home/dusatekc/mingook.dusatek.com/

    # 2. Find and Run NPM
    - cd /home/dusatekc/mingook.dusatek.com
    # This command finds the path to npm and runs 'install' in one go
    - $(which npm || find /opt/cpanel -name npm | head -n 1) install
    - $(which npm || find /opt/cpanel -name npm | head -n 1) run build

    # 3. Laravel Setup
    - composer install --no-interaction --optimize-autoloader --no-dev