deployment:
  tasks:
    # 1. Clear and Copy (The files now already contain the Vue build)
    - rm -rf /home/dusatekc/mingook.dusatek.com/*
    - cp -r /home/dusatekc/repositories/mingook/* /home/dusatekc/mingook.dusatek.com/
    - cd /home/dusatekc/mingook.dusatek.com

    # 2. Skip NPM entirely! (No more Out of Memory errors)

    # 3. Finalize Laravel
    - composer install --no-interaction --optimize-autoloader --no-dev
    - php artisan optimize:clear