deployment:
  tasks:
    - rm -rf /home/dusatekc/mingook.dusatek.com/*
    - cp -r /home/dusatekc/repositories/min-gook/* /home/dusatekc/mingook.dusatek.com/
    - cd /home/dusatekc/mingook.dusatek.com
    
    # Compile Vue/Assets
    - npm install
    - npm run build 

    # Install PHP dependencies
    - composer install --no-interaction --optimize-autoloader --no-dev