deployment:
  tasks:
    # 1. Clean and Copy code
    - rm -rf /home/dusatekc/mingook.dusatek.com/*
    - cp -r /home/dusatekc/repositories/mingook/* /home/dusatekc/mingook.dusatek.com/
    - cd /home/dusatekc/mingook.dusatek.com

    # 2. Build Vue Assets using the Node virtual environment
    - source /home/dusatekc/nodevenv/mingook.dusatek.com/20/bin/activate && npm install
    - source /home/dusatekc/nodevenv/mingook.dusatek.com/20/bin/activate && npm run build

    # 3. Finalize Laravel PHP dependencies
    - composer install --no-interaction --optimize-autoloader --no-dev