deployment:
  tasks:
    # 1. Clear and Copy code
    - rm -rf /home/dusatekc/mingook.dusatek.com/*
    - cp -r /home/dusatekc/repositories/mingook/* /home/dusatekc/mingook.dusatek.com/
    - cd /home/dusatekc/mingook.dusatek.com

    # 2. Run Composer using PHP
    - php composer.phar install --no-interaction --optimize-autoloader --no-dev