deployment:
  tasks:
    # 1. Clear and Copy code (Now including your local Vue build)
    - rm -rf /home/dusatekc/mingook.dusatek.com/*
    - cp -r /home/dusatekc/repositories/mingook/* /home/dusatekc/mingook.dusatek.com/
    - cd /home/dusatekc/mingook.dusatek.com

    # 2. Run Composer using the full path
    # On most cPanel servers, it is located at /usr/local/bin/composer
    - /usr/local/bin/composer install --no-interaction --optimize-autoloader --no-dev